@GolfTracker.API_HostAddress = http://localhost:5226

GET {{GolfTracker.API_HostAddress}}/api/golfcourse/courses
Accept: application/json

GET {{GolfTracker.API_HostAddress}}/api/golfscores/score
Accept: application/json

POST {{GolfTracker.API_HostAddress}}/api/golfscores/score
Content-Type: application/json
{
    "HoleNumber": 1,
    "Score": 4,
    "GolfCourseName": "Some Course",
    "DatePlayed": "2024-09-23"
}
